version: '3.8'

services:
  springbootapp:
    image: image_name:auth-service
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      DB_HOST: postgresdb
      DB_PORT: 5432
      DB_NAME: authentication
      DB_USERNAME: postgres
      DB_PASSWORD: Rajat@123

  postgresdb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: authentication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rajat@123